In [69]:
import pandas as pd
from pandas import DataFrame
import numpy as np
from bff_processor.SampleManager import SampleManager, SampleManagerPlotting
from bff_processor.SampleStack import SampleStack
from bff_processor.utils import make_view
import matplotlib.pyplot as plt
import mplhep as hep
import pprint
import matplotlib.gridspec as gridspec
hep.set_style(hep.style.CMS)

In [70]:
sample_list =[
['data/tw_2016_BFFZprimeToMuMu_M_200.csv', 'BFFZprimeToMuMu_M_200', 'BFFZprimeToMuMu_M_200', 'sig', 'blue'],
['data/tw_2016_BFFZprimeToMuMu_M_200_dbs0p5.csv', 'BFFZprimeToMuMu_M_200_dbs0p5', 'BFFZprimeToMuMu_M_200_dbs0p5', 'sig', 'blue'],
['data/tw_2016_BFFZprimeToMuMu_M_200_dbs1p0.csv', 'BFFZprimeToMuMu_M_200_dbs1p0', 'BFFZprimeToMuMu_M_200_dbs1p0', 'sig', 'blue'],
['data/tw_2016_BFFZprimeToMuMu_M_350.csv', 'BFFZprimeToMuMu_M_350', 'BFFZprimeToMuMu_M_350', 'sig', 'BFFZprimeToMuMu_M_350', 'sig', 'blue'],
['data/tw_2016_BFFZprimeToMuMu_M_350_dbs0p5.csv', 'BFFZprimeToMuMu_M_350_dbs0p5', 'BFFZprimeToMuMu_M_350_dbs0p5', 'sig', 'blue'],
['data/tw_2016_BFFZprimeToMuMu_M_350_dbs1p0.csv', 'BFFZprimeToMuMu_M_350_dbs1p0', 'BFFZprimeToMuMu_M_350_dbs1p0', 'sig', 'blue'],
['data/tw_2016_BFFZprimeToMuMu_M_500.csv', 'BFFZprimeToMuMu_M_500', 'BFFZprimeToMuMu_M_500', 'sig', 'blue'],
['data/tw_2016_BFFZprimeToMuMu_M_500_dbs0p5.csv', 'BFFZprimeToMuMu_M_500_dbs0p5', 'BFFZprimeToMuMu_M_500_dbs0p5', 'sig', 'blue'],
['data/tw_2016_BFFZprimeToMuMu_M_500_dbs1p0.csv', 'BFFZprimeToMuMu_M_500_dbs1p0', 'BFFZprimeToMuMu_M_500_dbs1p0', 'sig', 'blue'],
   
['data/tw_2016_ZToEE_M_120_200.csv', 'ZToEE_M_120_200', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToEE_M_200_400.csv', 'ZToEE_M_200_400', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToEE_M_400_800.csv', 'ZToEE_M_400_800', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToEE_M_50_120.csv', 'ZToEE_M_50_120', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToEE_M_800_1400.csv', 'ZToEE_M_800_1400', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToMuMu_M_120_200.csv', 'ZToMuMu_M_120_200', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToMuMu_M_200_400.csv', 'ZToMuMu_M_200_400', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToMuMu_M_400_800.csv', 'ZToMuMu_M_400_800', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToMuMu_M_50_120.csv', 'ZToMuMu_M_50_120', 'DY', 'bkc', 'red'],
['data/tw_2016_ZToMuMu_M_800_1400.csv', 'ZToMuMu_M_800_1400', 'DY', 'bkc', 'red'],
    
['data/tw_2016_mc_santitop.csv', 'mc_santitop', 'ST', 'bkc', 'green'],
['data/tw_2016_mc_stop.csv', 'mc_stop', 'ST', 'bkc', 'green'],
['data/tw_2016_mc_ttbar.csv', 'mc_ttbar', 'TT', 'bkc', 'orange'],
['data/tw_2016_mc_ww.csv', 'mc_ww', 'WW/WZ/ZZ', 'bkc', 'purple'],
['data/tw_2016_mc_wz.csv', 'mc_wz', 'WW/WZ/ZZ', 'bkc', 'purple'],
['data/tw_2016_mc_zz.csv', 'mc_zz', 'WW/WZ/ZZ', 'bkc', 'purple']]
    
sample_list_data =[
['data/tw_2016_data_el.csv', 'data_el', 'data', 'data', 'black'],
['data/tw_2016_data_mu.csv', 'data_mu', 'data', 'data', 'black'],
]

In [71]:
labels = [x[2] for x in sample_list]
labels = np.unique(labels)

In [72]:
stack = SampleStack(sample_list=sample_list)
stack_data = SampleStack(sample_list=sample_list_data)

('data/tw_2016_BFFZprimeToMuMu_M_200.csv', 'BFFZprimeToMuMu_M_200', 'BFFZprimeToMuMu_M_200', 'sig', 'blue')
('data/tw_2016_BFFZprimeToMuMu_M_200_dbs0p5.csv', 'BFFZprimeToMuMu_M_200_dbs0p5', 'BFFZprimeToMuMu_M_200_dbs0p5', 'sig', 'blue')
('data/tw_2016_BFFZprimeToMuMu_M_200_dbs1p0.csv', 'BFFZprimeToMuMu_M_200_dbs1p0', 'BFFZprimeToMuMu_M_200_dbs1p0', 'sig', 'blue')
('data/tw_2016_BFFZprimeToMuMu_M_350.csv', 'BFFZprimeToMuMu_M_350', 'BFFZprimeToMuMu_M_350', 'sig', 'BFFZprimeToMuMu_M_350', 'sig', 'blue')
('data/tw_2016_BFFZprimeToMuMu_M_350_dbs0p5.csv', 'BFFZprimeToMuMu_M_350_dbs0p5', 'BFFZprimeToMuMu_M_350_dbs0p5', 'sig', 'blue')
('data/tw_2016_BFFZprimeToMuMu_M_350_dbs1p0.csv', 'BFFZprimeToMuMu_M_350_dbs1p0', 'BFFZprimeToMuMu_M_350_dbs1p0', 'sig', 'blue')
('data/tw_2016_BFFZprimeToMuMu_M_500.csv', 'BFFZprimeToMuMu_M_500', 'BFFZprimeToMuMu_M_500', 'sig', 'blue')
('data/tw_2016_BFFZprimeToMuMu_M_500_dbs0p5.csv', 'BFFZprimeToMuMu_M_500_dbs0p5', 'BFFZprimeToMuMu_M_500_dbs0p5', 'sig', 'blue')

In [73]:
weights = [
['Weight_PuUp','Weight_PuDown'],
['Weight_BTagUp','Weight_BTagDown'],
['Weight_PUIDUp','Weight_PUIDDown'],
['Weight_PDF_ISRFSR_Up','Weight_PDF_ISRFSR_Down'],
['Weight_MuonSFUp','Weight_MuonSFDown'],
['Weight_ElectronSFUp','Weight_ElectronSFDown'],]
regions = ['SR{}_{{}}','CR{}0_{{}}', 'CR{}3_{{}}', 'CR{}4_{{}}']
nJets = [1,2]
jes_var = [['jesDown', 'jesUp'], ['jerDown', 'jerUp']]
BFF_cuts =  ['HTLT_{}', 'RelMET_{}', 'SBM_{}']
def def_BFF_cuts(jv, nJet):
    t1 =  [bff.format(jv) for bff in BFF_cuts]
    return(list(zip(t1,BFF_cut_values[nJet])))

BFF_cut_values ={1:[-18,.3125,18.75], 2:[-10,.2625,1.25]}
def make_view(jv,nJets, region): 
    bff = def_BFF_cuts(jv, nJet)
    view_dict = {'lt': {'DiLepMass': np.inf, bff[0][0]: bff[0][1], bff[1][0]: bff[1][1]},
         'gt': {'DiLepMass': -np.inf, bff[2][0]: bff[2][1]},
         'eq': {'Flag_METFilters': 1, region.format(nJets).format(jv): 1}}
    return view_dict

In [74]:
bins = np.linspace(100,800,int((800-100)/5+1))
bins

array([100., 105., 110., 115., 120., 125., 130., 135., 140., 145., 150.,
       155., 160., 165., 170., 175., 180., 185., 190., 195., 200., 205.,
       210., 215., 220., 225., 230., 235., 240., 245., 250., 255., 260.,
       265., 270., 275., 280., 285., 290., 295., 300., 305., 310., 315.,
       320., 325., 330., 335., 340., 345., 350., 355., 360., 365., 370.,
       375., 380., 385., 390., 395., 400., 405., 410., 415., 420., 425.,
       430., 435., 440., 445., 450., 455., 460., 465., 470., 475., 480.,
       485., 490., 495., 500., 505., 510., 515., 520., 525., 530., 535.,
       540., 545., 550., 555., 560., 565., 570., 575., 580., 585., 590.,
       595., 600., 605., 610., 615., 620., 625., 630., 635., 640., 645.,
       650., 655., 660., 665., 670., 675., 680., 685., 690., 695., 700.,
       705., 710., 715., 720., 725., 730., 735., 740., 745., 750., 755.,
       760., 765., 770., 775., 780., 785., 790., 795., 800.])

In [75]:
def make_sys_plots(stack, reg, nJet, ismc=0, **kwargs):
        n_jet_region  = reg.format(nJet)
        nom_region = n_jet_region.format('nominal')
        hist_dict = {}
        weight_dict = {}
        jv_dict = {}
        
        print(nom_region)
        BFF_cut = def_BFF_cuts('nominal', nJet)

        stack.view = make_view('nominal',nJet, reg)
        nom_hist = stack.sum_hists('DiLepMass', bins, **kwargs, w_kwargs={'weight_names':['Weight']})
        if ismc: 
            for up,down in weights:
                up_hist = stack.sum_hists('DiLepMass', bins, **kwargs, w_kwargs={'weight_names':[up]})
                down_hist = stack.sum_hists('DiLepMass', bins, **kwargs, w_kwargs={'weight_names':[down]})
                weight_dict[up] = [up_hist,down_hist]
                
            for up,down in jes_var:
                stack.view = make_view(up,nJet, reg)
                up_hist = stack.sum_hists('DiLepMass', bins, **kwargs, w_kwargs={'weight_names':['Weight']})
                stack.view = make_view(down,nJet, reg)
                down_hist = stack.sum_hists('DiLepMass', bins, **kwargs, w_kwargs={'weight_names':['Weight']})
                jv_dict[jv] = [up_hist,down_hist]
            
        hist_dict['nom'] = nom_hist
        if ismc:
            hist_dict['jv'] = weight_dict
            hist_dict['weights'] = jv_dict
        return hist_dict

In [ ]:
bins = np.linspace(100,800,int((800-100)/100+1))
import itertools
reg_list =  [[reg, nJet] for reg in regions for nJet in nJets]

reg_dict = {}
for reg, nJet in reg_list:
        hist_dict = {}
        if 'SR' not in reg:
            hist_dict["data"] = make_sys_plots(stack_data, reg, nJet)
        for label in labels:
            print(label)
            hist_dict[label] = make_sys_plots(stack, reg, nJet, ismc=1, label=label)
            
        reg_dict[reg.format(nJet)] = hist_dict
        break

BFFZprimeToMuMu_M_200
SR1_nominal


In [68]:
hist_dict

{'BFFZprimeToMuMu_M_200': {'nom': (array([4.89958138e+02, 3.82315234e+02, 2.06760807e-02, 0.00000000e+00,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
   array([3.33559058, 2.94637843, 0.02067608, 0.        , 0.        ,
          0.        , 0.        ]),
   array([100., 200., 300., 400., 500., 600., 700., 800.]),
   [150.0, 250.0, 350.0, 450.0, 550.0, 650.0, 750.0]),
  'jv': {'Weight_PuUp': [(array([4.82993118e+02, 3.77133665e+02, 1.96300488e-02, 0.00000000e+00,
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
     array([3.27375435, 2.89411987, 0.01963005, 0.        , 0.        ,
            0.        , 0.        ]),
     array([100., 200., 300., 400., 500., 600., 700., 800.]),
     [150.0, 250.0, 350.0, 450.0, 550.0, 650.0, 750.0]),
    (array([4.96789264e+02, 3.87354204e+02, 2.14515243e-02, 0.00000000e+00,
            0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
     array([3.45806774, 3.05114243, 0.02145152, 0.        , 0.        ,
            0. 

In [28]:
import pickle

In [35]:
with open('test.pkl','wb') as f:
    pickle.dump(hist_dict,f)

In [37]:
with open('test.pkl','rb') as f:
    hist_dict_temp = pickle.load(f)

In [38]:
hist_dict_temp

{'nom': (array([2073.61339259,  423.64186119,   88.9441923 ,   31.28633747,
           13.23890935,   11.6425238 ,    3.49388602]),
  array([166.51882591,  21.76781011,   9.29375952,   2.1704393 ,
           1.13082745,   3.774092  ,   0.53985817]),
  array([100., 200., 300., 400., 500., 600., 700., 800.]),
  [150.0, 250.0, 350.0, 450.0, 550.0, 650.0, 750.0]),
 'jv': {'Weight_PuUp': [(array([2041.47399978,  429.86527308,   90.92091193,   31.91912637,
             13.45764829,   10.8604999 ,    3.57356931]),
    array([162.56513167,  22.14550483,   9.40881239,   2.2459303 ,
             1.13540688,   3.05701057,   0.5493947 ]),
    array([100., 200., 300., 400., 500., 600., 700., 800.]),
    [150.0, 250.0, 350.0, 450.0, 550.0, 650.0, 750.0]),
   (array([2110.7747497 ,  417.10175924,   87.11495993,   30.61356392,
             13.03434258,   12.56287059,    3.43271228]),
    array([174.91875003,  21.79206741,   9.38127265,   2.12286231,
             1.14802231,   4.66002275,   0.55250568]